### ISSUE TITLE
Open in Visual Studio 2017

### ISSUE THREAD

**Issue by mrharris** [agrabhi/livs#1]
Would it be possible to get this working with visual studio 2017? I switched over from 2015 recently and am getting this when running livs
> Visual Studio not available on this machine.

Thanks a lot! Very handy extension

**Comment by agrabhi** [comment]
thanks for raising the requirement, I almost forgot. Will update the extension

**Comment by agrabhi** [comment]
Fixed, please try @mrharris  and reopen the issue, if it doesn't work.

**Comment by mrharris** [comment]
Thanks @agrabhi, though it's still not working for me. I wonder could it be that the path ends in a space? https://github.com/agrabhi/livs/blob/master/extension.js#L30

**Comment by agrabhi** [comment]
You are write... let me check

**Comment by agrabhi** [comment]
Updated it @mrharris ,please check and update

**Comment by mrharris** [comment]
Thanks. It's now behaving different, but still not working. I'm not sure if this is a problem local to me. Haven't tried any other machines
![image](https://cloud.githubusercontent.com/assets/1923447/25339743/9b67840c-28fb-11e7-866d-01f756a6c1aa.png)

**Comment by agrabhi** [comment]
I have tested it now for 2017 community and fixed an issue. It should work now for you as well. Please reply if it doesn't.
